### ISSUE TITLE
odftoolkit.org down

### ISSUE THREAD

**Issue by eMPee584** [tdf/odftoolkit#1]
404 : /

**Comment by mistmist** [comment]
this is a known problem, the ASF bureaucracy hasn't managed to transfer that domain to TDF yet so there's nothing we can do at this time.

**Comment by j-dimension** [comment]
Just out of curiosity: what level of support will TDF provide for the project?

**Comment by aadrian** [comment]
Since it seems to take that much time to get a simple site up, why not publish the content on GitHub (pages) too?

**Comment by svanteschubert** [comment]
Hello Jens,

What support do like you have?

Cheers,
Svante



Am Do., 14. Feb. 2019 um 12:37 Uhr schrieb Jens Kutschke <
notifications@github.com>:

**Comment by svanteschubert** [comment]
Yes, the former volunteer unfortunately was not able to finish (or even
start it) so someone else has to do some adoption to make it run.
If anybody willing to step forward to assist, that would be great and I
would put the markdown (and former tools) in a branch of the toolkit.

Thanks in advance,
Svante


Am Mo., 18. März 2019 um 12:31 Uhr schrieb aadrian <notifications@github.com

**Comment by j-dimension** [comment]
@svanteschubert thanks for the reply.

The question was actually not about me looking for support, but wondering what TDF will be doing to support this project.

I have an open source project (j-lawyer.org) that depends on ODF Toolkit for automated document generation. I would like to see your project succeed and prosper long-term.

**Comment by svanteschubert** [comment]
Hello Jens,

I can certainly not speak for TDF, but from my simple view the TDF is a
group of people interested in opensource related to office documents, not
driven by profit.
In other words, there are just volunteers and companies that might be using
parts of the ODF Toolkit, developing it further.
If you like that it prosper long-term, the best way is to participate in
any way.

I am a volunteer, who used to work for Sun/StarOffice on the ODFDOM being
used as a web editor's backend. And still I am dedicated to the ODFDOM (and
its generator) and so is Michael Stahl dedicated to the ODF Validator.
Michael and I both believe that the Simple API fork by IBM was a bad idea,
even worse not do undo it and to merge it when bringing it back to Apache.
Therefore we plan to discontinue to spend efforts in the Simple API. If you
take a look at the sources of the Simple API you will realize many parts of
ODFDOM have simply been copied to the Simple API and this code duplication
worries us a lot.

Good luck with your project, but remember to contribute a little bit from
time to time to keep the open source layer running.. ;-)

Cheers
Svante


Am Mo., 18. März 2019 um 14:44 Uhr schrieb Jens Kutschke <
notifications@github.com>:

**Comment by j-dimension** [comment]
Thanks Svante. The "open source layer" is actually full stack, because my project is open source, too (https://github.com/jlawyerorg). 

I am watching the odftoolkit repo since it moved to GitHub, so yes, I am receiving communication and am monitoring what issues are / will be coming in. I only know parts of the API (those that were relevant for me) but clearly would consider looking into "good first issue"s :-)

**Comment by svanteschubert** [comment]
I will fly to Iceland for a week from next Thursday and will be offline (4 days holidy & 2 days e-Invoice CEN plenary meeting).

So I have once again tackled the website and uploaded the entire old sources to a separate GitHub repro:
https://github.com/svanteschubert/odftoolkit_website
1. Unnecessary files deleted
2. The generation got up and running from the old Linux Ubuntu VirtualBox, but it did not work on a new Ubuntu version.
3. The generated HTML is loaded into the githubRepro / docs directory
4. The GitHub Repro website activated
5. After a few iterations, the old website got up and running without broken links:
https://svanteschubert.github.io/odftoolkit_website/index.html

What else needs to be changed?

a) Instead of just copying copyright & Apache stuff in the Skelletton template in all HTML files:
https://github.com/svanteschubert/odftoolkit_website/blob/master/site/templates/skeleton.html

b) And as usual the graphics were exchanged (or only one):
https://github.com/svanteschubert/odftoolkit_website/tree/master/site/content/odftoolkit_website/images

c) And the light blue and yellow of the CSS are changed:
https://github.com/svanteschubert/odftoolkit_website/blob/master/site/content/odftoolkit_website/css/odf.css

Question for anyone:
1) Are there any volunteers for the above editing tasks? Or at least a part?
3) Could someone try to get the generation running under Linux:
https://svanteschubert.github.io/odftoolkit_website/website-local.html#setup
And already adjust the docu?

I freely give commitright to this repro for any takers.. ;-)

**Comment by svanteschubert** [comment]
Some notes on the generation of the site:
https://svanteschubert.github.io/odftoolkit_website/website-local.html#setup

The described below will not work:
`sudo easy_install Pygments`
`sudo easy_install ElementTree`
`sudo easy_install Markdown`
It is not working any longer as `easy_install` is no longer part of the setuptools.

It worked for me as I was working on Ubuntu 18.04 with Python 2.7.15rc1 I installed the dependencies via
`sudo apt-get install -y python2.7-elementtree`
`sudo apt install python-pip`
`python -m pip install "Markdown<2.6.0"`
`python -m pip install "Pygments==2.2.0"`

These were my last versions which worked finally.
I tried and failed with other things earlier, always after the export line:
export MARKDOWN_SOCKET=`pwd`/markdown.socket PYTHONPATH=`pwd`
with 
`python cms/build/markdownd.py`
Traceback (most recent call last):
  File "cms/build/markdownd.py", line 43, in <module>
    dummy = markdown.markdown(unicode("", "utf-8"), EXTENSIONS)
TypeError: markdown() takes exactly 1 argument (2 given

But finally it worked. Could someone try it as well, please? 
Likely works only on Linux and not on Windows due to the socket file.

**Note:** When I run 
`cms/build/build_site.pl` --source-base site --target-base www`
I got as well the following warning, but all works well:
Can't open cgi-bin [skipping]: No such file or directory at cms/build/build_site.pl line 126.
Likely as we have a lib and not cgi-bin directory as mentioned in the [main Apache CMS documentation](http://www.apache.org/dev/cmsref.html#local-build) (which is as well outdated).

**Comment by svanteschubert** [comment]
Thorsten was so kind to add a preliminary page at odftoolkit.org
Meanwhile I continue to edit my clone and embraced the mayority of his changes: https://svanteschubert.github.io/odftoolkit_website

Will continue with it from time to time over the next days..

**Comment by svanteschubert** [comment]
As I will be offline for at least a week (visting Iceland) I have copied my current work on the website you see at
https://svanteschubert.github.io/odftoolkit_website/index.html
from the sources at https://github.com/svanteschubert/odftoolkit_website/docs
to a branch of this main project, resorted the resources and continued my work from there
https://github.com/tdf/odftoolkit/tree/website

The site creation tooling can be found under
https://github.com/tdf/odftoolkit/tree/website/src/site

There is the Apache CMS 
https://github.com/tdf/odftoolkit/tree/website/src/site/cms
the content markdown
https://github.com/tdf/odftoolkit/tree/website/src/site/site/content/odftoolkit_website
which was pimped up by some scripts to allow creating a HTML page from multiple templates:
https://github.com/tdf/odftoolkit/tree/website/src/site/site/templates
and some references will be resolved by these scripts.

I started some new bash scripts (site tooling is used by myself only on Linux) to ease usability.
One of the two new scripts is
https://github.com/tdf/odftoolkit/blob/website/src/site/create-and-copy-html.sh
calling it will create the HTML from Markdown and update the GitHub site - viewing the content from:
https://github.com/tdf/odftoolkit/tree/website/docs
(for more info on GitHub pages take a look at: https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/)
I am currently in the middle of exchanging the absolute path "/odftoolkit_website/" from the generated HTML with a relative path dependent on the depth of the HTML file with bash (or at least I have asked Thorsten & Michael to assist me doing it) ;-)

The second bash script in-spe should be to removing and coping the JavaDoc API from the various projects to:
https://github.com/tdf/odftoolkit/tree/website/docs/api

I have fixed & updated the pom.xml of the projects, so the JavaDoc title and a new bottom copyright line is added.
Fixed "mvn site" and made sure that with "mvn install" also the JARs for JavaDoc are being created (tested on Windows & Linux). Somehow the cobertura code coverage does no longer work for ODFDOM, but it is a problem of the lib problem and I disabled it for now.

There are still some Apache incubator mentioning on the site and it might take some further evenings to update all the markdown files. Especially the mailing list is the old one, we might start with going to the high traffic LO dev list as Thorsten has suggested it, perhaps using ODF as start/part of the mail subject to ease the search.

**Comment by derrg** [comment]
As far as a website is concerned, would it make sense to maybe have `odftoolkit.org` redirect to GitHub Pages? That way the website and the code are maintained in the same repo. :)

**Comment by svanteschubert** [comment]
Before of my short vacation I have worked on the web site via
https://github.com/svanteschubert/odftoolkit_website
this should be moved - [according to Maven's default directory structure](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) - to 
https://github.com/tdf/odftoolkit/src/site

You are currently viewing the HTML sources at:
https://svanteschubert.github.io/odftoolkit_website/index.html
so the latest sources should be viewable in the future at
https://tdf.github.io/odftoolkit/index.html
which will be likely basically copied to:
odftoolkit.org

The next step would be a bash script (as the Apache site tooling works best on Linux) to exchange the absolute path "/odftoolkit_website/" from the generated HTML with a relative path dependent on the depth of the HTML file. Perhaps someone could drop me an email, if a helping hand could be borrowed.. :-)

Cheers,
Svante

**Comment by mistmist** [comment]
apparently Svante was able to point odftoolkit.org to an actual web server recently, so there's progress :)

**Comment by svanteschubert** [comment]
We have updated: https://odftoolkit.org/
The latest version will be available at: https://tdf.github.io/odftoolkit/docs/

Editing the website is derived from Apache tooling and easiest to be setup under Linux:
https://tdf.github.io/odftoolkit/docs/website-local.html

I am working now on the update of the documentation of ODFDOM and continue to do minor fixes to the website.
