### ISSUE TITLE
Add FAQ: "How to find an API for an ODF Feature" - initially "How to add hyperlink(ods)"

### ISSUE THREAD

**Issue by z24500112** [tdf/odftoolkit#126]
Question as title
thanks

**Comment by svanteschubert** [comment]
Hej, I am sorry, I must have overseen this issue notification somehow in my flood of emails...
If no one answers within a few days, just ping please again with a reminder (still I try to improve my mail handling)...
Aside from this, I would suggest asking in general at a dev mailing list: https://tdf.github.io/odftoolkit/mailing-lists.html

# How to find an API in the ODFDOM (of ODF TOOLKIT)

I can not remember any API I am not using frequently, so I do the following

## Are there Test using/testing the functionality?

first usually quickly look into the test of the source code, such as via command line:

git clone https://github.com/tdf/odftoolkit.git odftoolkit-latest-0.10.0
cd odftoolkit-latest-0.10.0/odfdom/src/test
find . -name *.java | xargs grep hyper

Here: The results are just within the changes packages, which is the new Event API (similar to SAX) only supporting ODT (not ODS yet).

## What XML is being used for the feature? Test it in LibreOffice

What is always working is to use the DOM API. But you need to know what XML is being used for your feature!
Test it! 
You may use LibreOffice to add a simple hyperlink in a cell save it, unzip it and take a look into the XML..
(I am using JEdit with the Archive and XML Indent Plugin as I have not found time to write a Visual Studio Code ODF extension)

There I find my test file and you see how a hyperlink works: 
<table:table-cell office:value-type="string"><text:p>mytest<text:a xlink:href="https://www.heise.de/" xlink:type="simple">heiseLink</text:a></text:p>

## Check the ODF Specification & ODF Grammar

Now, when you know what is the XML node you might look into the ODF specification for more information:

https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part3-schema/OpenDocument-v1.3-os-part3-schema.html#element-text_a

Or in the grammar: 
http://docs.oasis-open.org/office/OpenDocument/v1.3/os/schemas/OpenDocument-v1.3-schema-rng.html#16201

(Michael and I are now ODF TC editors, but I was not yet capable to add JavaScript that adds the line number when you press the line number ahead of the line - as it does in GitHub - PullRequest are welcome: 
https://github.com/tdf/odftoolkit/blob/master/xslt-runner/src/test/resources/HowTo.md
but we might want to move it sooner or later to
https://github.com/oasis-tcs/odf-tc)

All ODF XML is reused across the ODF document formats, therefore  Hyperlink XML is the same for ODT and ODS 

## Find the ODF Element/Attribute in the ODFDOM API

You may find the element in the "typed" DOM element <text:a> by a certain pattern ->
https://github.com/tdf/odftoolkit/blob/master/odfdom/src/main/java/org/odftoolkit/odfdom/dom/element/text/TextAElement.java


## Check in your IDE the ODFDOM node class for usage by High-Level API classes

Now you might check in your favourite Java IDE (I am using Netbeans, IntelliJ and VSCode) what classes are using this class.
By this, you will see that the parent DOM elements (e.g. TextPElement) have a function to add a Hyperlink.

PS: Yes, this can be done better and I received some funding from NGI NL.net Zero to improve this situation but had to postpone the project to March next year (due to other conflicting projects).

**Comment by svanteschubert** [comment]
@z24500112 
Hope that could help you (I assume you had helped yourself in the past 2,5 months) ;-)
Let's keep this issue in as a documentation issue (FAQ: how to find an API), in general, I would suggest asking future questions on the list (see link above), otherwise, it is difficult to decide when to close an issue... :-)
