### ISSUE TITLE
Adding branch for ODF Toolkit 1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by svanteschubert** [tdf/odftoolkit#13]
I have suggested and discussed with Michael Stahl, Oliver Rau and Thorsten Behrens to add a new branch for ODF Toolkit 1.0.0-SNAPSHOT.

I am afraid this branch is a huge jump and contains years of work on new features and fixes.

It had been triggered by the [sponsoring of the German PrototypeFund in Winter 2017/2018](https://prototypefund.de/project/documents-for-democracy/) and I continued in the past year my work on the collaboration feature of this branch:
https://github.com/svanteschubert/odftoolkit/tree/odf-changes

In addition, this branch has many many fixes and feature enhancements from my work as a freelancer for the German Open-Xchange GmbH, which forked ODF Toolkit and use this collaboration features for the [OX Documents web office](https://www.open-xchange.com/portfolio/ox-documents/) and started to work on a fork before I even started there. During my working time there was never time to merge the work back...until I worked on it end of last year in my winter holidays.

**The idea of the new collaboration feature in a nutshell**: If multiple editors are working on copies of the same document, but would like to have a single document in the end, they need to ask the others for their changes on the document to merge them back. Unfortunately, not a single file format in the whole world is defining such changes, but only specifying the full file format for interoperability. But sending the full document for collaboration among applications is as clever as if software developers would collaborate in programming by zipping source code repositories and attaching those to emails for their co-works.

Therefore this new library is able to load an ODF Text document (ODT) and dissamble the document into an equivalent sequence of high-level user changes. Executing this sequence of user changes would create the same document, by writing it from the top to the bottom.
This list of high-level user changes is in created as JSON to be dispatched to browser offices (see the [example JSON file](https://github.com/svanteschubert/odftoolkit/blob/odf-changes/character-styles.json) and equal [ODT file](https://github.com/svanteschubert/odftoolkit/blob/odf-changes/character-styles.odt)).
A browser office will receive the same changes from users as from a loaded document.

See [my presentation on the LibreOffice Conference 2018](https://github.com/svanteschubert/odftoolkit/blob/odf-changes/LibOCon2018%20%20-%20Interoperable%20Office%20Collaboration.pdf) for more detailed information.

The upcoming new website should have more explicit information about this new feature and especially a high-level view from the design of this feature and its pro/cons.

**Comment by svanteschubert** [comment]
Right after our next release, our plan is to let this branch become our the new master.
Removing the Simple API (sources and website documentation) and merging updates since New Years Day, such as .gitignore, travis, performance tests, etc.)

**Comment by svanteschubert** [comment]
I have added support for JDK 9 / 10 / 11 / 12 to [this branch](https://github.com/svanteschubert/odftoolkit/tree/odf-changes).
From JDK 1.8 to JDK 9 the tools.jar became an implementation detail. We used it for generating taglets [the HTML reference within JavaDoc of an ODF element, attribute or datatype that directly references to the ODF 1.2 specification].
With JDK 9 they added a new API for Taglets, so I have rewritten our taglets classes and dropped all tools.jar references.
Downside, this taglet project can from now on only be compiled with JDK 9 or higher.
Still fine with me.. ;-)

Took me several days to eliminate all obstacles, but I am happy that we have a [JDK 8 branch](https://github.com/tdf/odftoolkit/tree/MavenCleanup) and [JDK 11 branch](https://github.com/svanteschubert/odftoolkit/tree/odf-changes) now compiling without further naming/license problems, without any compiling or test errors (aside those from JavaDoc - I did not take the time to fix). I build with latest JDK 12 on a JDK 11 long-term-support (LTS) code base.

**Comment by 0x000eHx** [comment]
Hey there,
till now I did work with the odftoolkit version 0.9.
I did compare columns of two big ODF Spreadsheet Files (.ods) with macros and a lot of other settings.
Now I wanted to update to the odftoolkit verison 1.0.0 snapshot while using the latest Java 12 (12.0.2) and get a special Error, while using the org.odftoolkit.odfdom.doc.* namespace classes.
In verison 0.9 there were no errors with the org.odftoolkit.simple.SpreadsheetDocument etc classes.

I didn't get the right clue from the IDEAD IntelliJ Debugger or I don't know all capibilities yet.
The error stack trace states a heap size problem:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.cacheTableOperation(ChangesFileSaxHandler.java:2239)
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.cacheOperation(ChangesFileSaxHandler.java:2218)
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.endElement(ChangesFileSaxHandler.java:1722)
	at org.odftoolkit.odfdom.pkg.rdfa.MultiContentHandler.endElement(MultiContentHandler.java:90)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:236)
	at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:70)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:105)
	at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:59)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getContentDom(OdfSchemaDocument.java:412)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getTables(OdfSchemaDocument.java:640)
	at org.odftoolkit.odfdom.doc.OdfDocument.getTableList(OdfDocument.java:737)
	at Comparison.<init>(Comparison.java:43)
	at Main.main(Main.java:6)
```
I did increase it till `-Xms1024m -Xmx8000m` in the project VM Options, but this just fills my memory more and won't help.

My steps so far:
After I cloned your 1.0.0_SNAPSHOT inside IntelliJ and build the .jars with the Maven Options 'install -DskipTests' I did only insert 'odfdom-java-1.0.0-SNAPSHOT-jar-with-dependencies.jar' as a project dependency.
Thats it. Is there something missing? It's not missing any classes, so I can't suggest anything.

I found out while stepping through the code, that inside the method 'initialize(DefaultHandler handler, OdfFileDom dom)' in 'OdfFileDom.java' it triggers the methode 'xmlReader.parse(xmlSource)' and after this invocation, my memory gets filled up till break down.
But stepping inside this .parse methode shows some decompiled xerces source files for which IntelliJ states, that they don't match the java bytecode. It won't help when I insert the Xerces_2.12.0 source files as project dependencies so I cant really look very deep into the problem.

=========================================================
As comparison I did write a very small program with the code which gets invoked till it breaks down.
To proof anything I created two new Spreadsheet Documents with only one table and a little content inside each.
With these sheets my small program doesn't have any problem to give out the tables. getTableList() is working as expected.
Sorry, I can't paste the big Spreadsheet Documents here, cause they contain sensible data.

Can someone give me any hints?
I hope I didn't produce a unique error there...

I'll stay with my 0.9 builds, till that issue is solved. I can't build working jar files from the odftoolkit master branch here at the moment :roll_eyes: 

Thanks in advance
eHx

**Comment by svanteschubert** [comment]
Hi,

the feature to split a document into user changes (serialized to JSON)
should only work for a text document.
The feature that causes this problem is that every table is first being
cached to be counted and estimate its size.
Very huge tables were disabling the browser front-end from Open-XChange (OX
Documents <https://www.open-xchange.com/portfolio/ox-documents/>) and a
replacement image was inserted instead.
I am currently still in Salamanca (Spain) and next week at the ACM Document
Engineering conference in Berlin, but likely I will find some time to look
into it.
My general suggestion would have been any way to enable the user change
feature only when opening explicitly a CollabTextDocument and use the
former SaxHandler of the pkg Package for other OdfDocuments instead.

Saludos de Espana!
Svante

Am Di., 17. Sept. 2019 um 14:28 Uhr schrieb 0x000eHx <
notifications@github.com>:

**Comment by 0x000eHx** [comment]
So I guess in odftoolkit 0.9 the Simple Api classes do what you suggest?
I might try comparing the relevant Simple Api classes with the ODFDOM classes, if I find the time.

**Comment by svanteschubert** [comment]
We will drop the Simple API fork in 0.0.9 as there are too many code
duplications and the user changes feature is added on the 1.0.0 branch to
ODFDOM. Just in case we are cross-talking.. :)

Any help is very much appreciated as there are other 'corners' I have spent
time on.
Might sent my ACM poster session draft tomorrow ;)

**Comment by svanteschubert** [comment]
I was able to fix this on my flight back from Madrid.. :-)

The trick is to enable the new FileSaxHandler creating the user changes ONLY if the collab feature was explicitly set - by creating a CollabTextDocument...

Therefore within the OdfContentDom and OdfStylesDom class get a new conditional in their initialize method:

if(mPackageDocument instanceof OdfTextDocument && ((OdfDocument) mPackageDocument).hasCollaboration()){
    super.initialize(new ChangesFileSaxHandler(this), this);
}else{
    super.initialize(new OdfFileSaxHandler(this), this);
}

To keep the existing API, I have added a new boolean parameter.
If you like to suggest a different solution (or tweak simply overwrite my changes and we can discuss them) as long the tests are all working everything is fine.. ;-)

PS: I just updated the 1.0.0-SNAPSHOT branch...

**Comment by 0x000eHx** [comment]
Thanks for your fast response, I'll test it after my holidays. No other suggestions so far :P
