### ISSUE TITLE
No release tags available

### ISSUE THREAD

**Issue by veita** [tdf/odftoolkit#130]
The commits that correspond to the releases announced in the README.md are not identifiable. This makes building this releases difficult.

See https://github.com/tdf/odftoolkit/releases

**Comment by mistmist** [comment]
the tag for the upcoming 0.10 was:
odftoolkit-1.0.0-BETA1

while for the upcoming 0.9 there were:
odftoolkit-0.9.0-RC2
odftoolkit-0.9.0-RC1

but these are all very old and there have been significant changes on both branches since then, such as ODF 1.3 support in the validator, and of course the 1.0 was renamed to 0.10.

i don't know what remains to be done for a new release to happen but Svante said he's working on it.

**Comment by svanteschubert** [comment]
We have finally released 0.9.0 and 0.10.0 (including validated tags) :-)
