### ISSUE TITLE
Create a full copy of a spreadsheet in an ODF Spreadsheet document using the ODF Toolkit.

### ISSUE THREAD

**Issue by pe1999** [tdf/odftoolkit#313]
I need to create a full copy of a table sheet in an ODF Spreadsheet document using ODF Toolkit.
I'm trying to clone like this:

`ods.getContentRoot().appendChild(ods.getContentRoot().getChildNodes().item(1).cloneNode(true));`

The copy is created, but incorrectly. When opening the saved file with OpenOffice Calc - the cell formatting is not copied, when opening in Microsoft Excel - the cells are not filled in the copy. I use ODF Toolkit version 0.12.0.

**Comment by svanteschubert** [comment]
Hi there, please add a GitHub branch (Draft Pull Request), which includes a test (and a test document) that makes the problem easily reproducible.  If you do so, I promise to take a quick look at the problem immediately! 
Manus lavat manum! :-)

Thanks in advance!
Svante

**Comment by pe1999** [comment]
Hi!
I can't make a Draft Pull Request yet.
I created a separate repository with a test project.
https://github.com/pe1999/odftoolkit-test

**Comment by svanteschubert** [comment]
@pe1999 Thanks for the test and test document!
Promise made, promise kept! I fixed the cloning problem! ;-)
Your test is now part of `org.odftoolkit.odfdom.doc.table.TableTest` I slightly varied to make it easier to read (but I am fully aware that this is totally subjective and beg your pardon if I made things worse ;-) )
The problem was that the OdfElement.cloneNode() function explicitly `@office:value` and `@office:value-type` not cloned - which is not only hard to understand but even wrong as `@office:value-type` is a mandatory attribute! 
So many thanks for pointing this out! Have a nice week...

**Comment by pe1999** [comment]
Excellent!
Everything works great!
Thank you for the promptness!

**Comment by svanteschubert** [comment]
My pleasure, but the promptness was rather an accident...
In the future, you should be aiming to solve the problems yourself.

The recipe for solving:
1. Place the test in the latest ODF Toolkit environment (the loading/saving is a bit different, but simply copy paste from existing tests - 
2. Take a look at the XML output (here you can even compare it with the original)
3. Debug the

**Comment by pe1999** [comment]
@svanteschubert
Thank you very much, I will definitely use your recommendations.
I just started using odftoolkit. I wanted to create a Draft Pull Request as you recommended, but I had an unexpected problem with access to the Maven repositories and I just couldn't build the project, I hope the problem will be solved by my Internet provider in the near future.
