### ISSUE TITLE
Memory Leak in ODF Simple API

### ISSUE THREAD

**Issue by kl0ck** [tdf/odftoolkit#39]
Hello, can you check if this issue is resolved/fixed? They say it was fixed but we use this API in a project and the memory is leaking.

https://issues.apache.org/jira/browse/ODFTOOLKIT-300?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel%3D16369140#comment-16369140

**Comment by mistmist** [comment]
hi kl0ck,
the "Simple API" is deprecated so nobody is going to investigate this.
it's possible that the memory leak has a different cause than what was fixed in that old issue, but only investigation can reveal the reason.
but if you manage to find the problem and provide a patch we can add it to the 0.9.0 release branch :)

**Comment by kl0ck** [comment]
What is the replacement for the "Simple API"? Is there an easy way to replace the simple API without generating side effects?

**Comment by svanteschubert** [comment]
> What is the replacement for the "Simple API"? Is there an easy way to replace it without generating side effects?

The short answer is there is yet none and no.

Within the ODFDOM library, there is the 'in favour of the Simple API still deprecated' Java Package 'doc', that was the basement for the Simple API once forked by IBM. 
When Oracle the ODF Toolkit, IBM donated the Simple API back. Unfortunately, they did not merge it back into the ODFDOM, nor removed the copied code.

In the ODFDOM 1.0.0_SNAPSHOT branch is a new way to address changes to ODF text documents: https://tdf.github.io/odftoolkit/docs/odfdom/operations/operations.html
These operations were not applicable to the Simple API due to the heavy amount of copied code.

But there should be in the future indeed a high-level semantic API, similar to the Simple API, Let's call it semantic DOM. 
I am willing to work on the Semantic DOM basic layout, but existing functionality (e.g. from Simple API) has to be moved/transformed by the users who desire it.

With 'side effects' I assume you mean API changes. 
There will be likely manual API changes, unless you - or anyone else - is aware of a tool assisting in API changes. 
It is strange, I can do in Netbeans (once in Eclipse, likely in IDEA as well) explicit refactoring (like changing a method name), which is being applied to all open projects. 
Why am I not able to save these changes and apply them later to projects like in a batch processing?


With 'side effects' I assume you mean API changes. 
There will be likely manual API changes unless you - or anyone else - is aware of a tool assisting in API changes. 
It is strange, I can do in Netbeans (once in Eclipse, likely in IDEA as well) explicit refactoring (like changing a method name), which is being applied to all open projects. 
Why am I not able to save these changes and apply them later to projects like in a batch processing?

**Comment by danielftavares** [comment]
I just created the pull request #49 fixing this bug.
I work with @kl0ck  :)

**Comment by svanteschubert** [comment]
Commit with SHA 1b20ee5 fixes this issue on the master branch
