### ISSUE TITLE
https://odftoolkit.org is dead.

### ISSUE THREAD

**Issue by debuglevel** [tdf/odftoolkit#65]
In the meantime, it is available at https://tdf.github.io/odftoolkit/

**Comment by svanteschubert** [comment]
Thx, I have pinged the admin.. but no feedback, yet

**Comment by debuglevel** [comment]
Lives again! :-)

**Comment by debuglevel** [comment]
But https://tdf.github.io/odftoolkit/ and https://odftoolkit.org are out of sync, aren't they?

**Comment by svanteschubert** [comment]
> But https://tdf.github.io/odftoolkit/ and https://odftoolkit.org are out of sync, aren't they?

Hej Marc, a thousand thanks, sometimes things simply vanish from my radar due to too much "noise".
I have contacted Thorsten (Behrens) that he should no longer manual copy, but we establish a Git repository at odftoolkit.org.
Perhaps with the additional backup of releases (and even issue tracker if possible  ;-) )
